### ISSUE TITLE
external_components for [ esp32_camera ]

### ISSUE THREAD

**Issue by StrobesAV** [MichaKersloot/esphome_custom_components#4]
Hi, first of all, this is first time I using github to report an issue. So my apology if it is done unusual way.

I'm running  Home assistant 2025.7.2. An my intention is to configure ESP32S3_EYE
  [Freenove ESP32-S3-DevKitC-1](https://github.com/Freenove/Freenove_ESP32_S3_WROOM_Board)
It works fine in Arduino IDE.
Now I did follow this documentation with example for this particular camera. 
[ESP32 Camera Component — ESPHome](https://esphome.io/components/esp32_camera.html) 
Which did not work.
And the this one below published here does not work either.
Some details are in this post with logs: https://community.home-assistant.io/t/external-components/913187/3
Just to mention one of the forum members says that example published on esphome.io works ok in HA 2025.7 
And advise was to contact the author of the component.

external_components:
  - source:
      type: git
      url: https://github.com/ssieb/esphome_components
    components: [ component1, component2 ]

Errors when attempt made to validate the YAML

INFO ESPHome 2025.7.2
INFO Reading configuration /config/esphome/camera.yaml...
ERROR Unable to import component esp32_camera:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 200, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/data/external_components/0337b9f5/components/esp32_camera/__init__.py", line 20, in <module>
    from esphome.cpp_helpers import setup_entity
ImportError: cannot import name 'setup_entity' from 'esphome.cpp_helpers' (/esphome/esphome/cpp_helpers.py)
Failed config

esp32_camera: [source /config/esphome/camera.yaml:41]
  
  Component not found: esp32_camera.

**Comment by netmindz** [comment]
my config was working, now after update i am also seeing Component not found: esp32_camera.
